"""initial migration

Revision ID: 376522bac822
Revises: 
Create Date: 2025-12-10 19:24:54.975672-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '376522bac822'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_subscriptions')
    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.alter_column('unidad_residencial',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_administradores_id'), ['id'], unique=False)

    with op.batch_alter_table('escaneos_qr', schema=None) as batch_op:
        batch_op.alter_column('fecha_escaneo',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_escaneos_qr_id'), ['id'], unique=False)
        batch_op.drop_column('entidad_id')

    with op.batch_alter_table('guardias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guardias_id'), ['id'], unique=False)

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.alter_column('fecha_envio',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_notificaciones_id'), ['id'], unique=False)
        batch_op.drop_column('entidad_id')

    with op.batch_alter_table('residenciales', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_residenciales_id'), ['id'], unique=False)

    with op.batch_alter_table('residentes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_residentes_id'), ['id'], unique=False)

    with op.batch_alter_table('social', schema=None) as batch_op:
        batch_op.alter_column('residencial_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('requiere_respuesta',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('para_todos',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_social_id'), ['id'], unique=False)

    with op.batch_alter_table('social_destinatarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_destinatarios_id'), ['id'], unique=False)

    with op.batch_alter_table('social_imagenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_imagenes_id'), ['id'], unique=False)

    with op.batch_alter_table('social_opciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_opciones_id'), ['id'], unique=False)

    with op.batch_alter_table('social_votos', schema=None) as batch_op:
        batch_op.alter_column('fecha_voto',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_social_votos_id'), ['id'], unique=False)

    with op.batch_alter_table('super_admins', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
        batch_op.drop_index('idx_super_admins_usuario_id')
        batch_op.drop_index('unique_super_admin_usuario')
        batch_op.create_index(batch_op.f('ix_super_admins_id'), ['id'], unique=False)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_tickets_id'), ['id'], unique=False)
        batch_op.drop_constraint('tickets_residencial_id_fkey', type_='foreignkey')
        batch_op.drop_column('residencial_id')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('fecha_actualizacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('visitantes', schema=None) as batch_op:
        batch_op.alter_column('tipo_vehiculo',
               existing_type=sa.VARCHAR(length=70),
               nullable=False)
        batch_op.alter_column('motivo_visita',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_visitantes_id'), ['id'], unique=False)

    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.alter_column('qr_expiracion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('fecha_salida',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_visitas_id'), ['id'], unique=False)
        batch_op.drop_column('entidad_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entidad_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_visitas_id'))
        batch_op.alter_column('fecha_salida',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('qr_expiracion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("(CURRENT_TIMESTAMP + '1 day'::interval)"),
               existing_nullable=True)

    with op.batch_alter_table('visitantes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitantes_id'))
        batch_op.alter_column('motivo_visita',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('tipo_vehiculo',
               existing_type=sa.VARCHAR(length=70),
               nullable=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))
        batch_op.alter_column('fecha_actualizacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residencial_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tickets_residencial_id_fkey', 'residenciales', ['residencial_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_tickets_id'))
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('super_admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_super_admins_id'))
        batch_op.create_index('unique_super_admin_usuario', ['usuario_id'], unique=True)
        batch_op.create_index('idx_super_admins_usuario_id', ['usuario_id'], unique=False)
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('social_votos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_votos_id'))
        batch_op.alter_column('fecha_voto',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('social_opciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_opciones_id'))

    with op.batch_alter_table('social_imagenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_imagenes_id'))

    with op.batch_alter_table('social_destinatarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_destinatarios_id'))

    with op.batch_alter_table('social', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_id'))
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
        batch_op.alter_column('para_todos',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
        batch_op.alter_column('requiere_respuesta',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
        batch_op.alter_column('residencial_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('residentes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_residentes_id'))

    with op.batch_alter_table('residenciales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_residenciales_id'))
        batch_op.alter_column('fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entidad_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_notificaciones_id'))
        batch_op.alter_column('fecha_envio',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('guardias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guardias_id'))

    with op.batch_alter_table('escaneos_qr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entidad_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_escaneos_qr_id'))
        batch_op.alter_column('fecha_escaneo',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)

    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_administradores_id'))
        batch_op.alter_column('unidad_residencial',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    op.create_table('vistas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('vistas_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vistas_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('p256dh_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('auth_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='push_subscriptions_usuario_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='push_subscriptions_pkey')
    )
    op.create_table('vistas_residencial',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('residencial_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vista_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activa', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['residencial_id'], ['residenciales.id'], name='vistas_residencial_residencial_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vista_id'], ['vistas.id'], name='vistas_residencial_vista_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='vistas_residencial_pkey')
    )
    op.create_table('vistas_admin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vista_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activa', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['administradores.id'], name='vistas_admin_admin_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vista_id'], ['vistas.id'], name='vistas_admin_vista_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='vistas_admin_pkey')
    )
    # ### end Alembic commands ###
