"""sync all models

Revision ID: 163b055bbefa
Revises: 376522bac822
Create Date: 2025-12-10 19:50:57.289310-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163b055bbefa'
down_revision: Union[str, None] = '376522bac822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vistas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vistas_id'), ['id'], unique=False)

    op.create_table('vistas_residencial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residencial_id', sa.Integer(), nullable=False),
    sa.Column('vista_id', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['residencial_id'], ['residenciales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vista_id'], ['vistas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vistas_residencial', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vistas_residencial_id'), ['id'], unique=False)

    op.create_table('vistas_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('vista_id', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['administradores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vista_id'], ['vistas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vistas_admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vistas_admin_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vistas_admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vistas_admin_id'))

    op.drop_table('vistas_admin')
    with op.batch_alter_table('vistas_residencial', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vistas_residencial_id'))

    op.drop_table('vistas_residencial')
    with op.batch_alter_table('vistas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vistas_id'))

    op.drop_table('vistas')
    # ### end Alembic commands ###
