"""delete note column how null to tickets now if

Revision ID: 94e89dfc1b79
Revises: 883795179e42
Create Date: 2025-12-10 20:32:01.679463-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e89dfc1b79'
down_revision: Union[str, None] = '883795179e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('notas')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notas', sa.TEXT(), server_default=sa.text("'Sin notas'::text"), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
