"""add is_active to push_suscriptions

Revision ID: c442f9ba7850
Revises: 85e06a68a4e5
Create Date: 2026-02-22 09:31:44.637682-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c442f9ba7850'
down_revision: Union[str, None] = '85e06a68a4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escaneos_qr', schema=None) as batch_op:
        batch_op.drop_constraint('escaneos_qr_uuid_evento_key', type_='unique')
        batch_op.drop_column('uuid_evento')
        batch_op.drop_column('registrado_offline')

    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('last_used', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)

    with op.batch_alter_table('residenciales', schema=None) as batch_op:
        batch_op.alter_column('activa',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)

    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_column('last_used')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('escaneos_qr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registrado_offline', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uuid_evento', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('escaneos_qr_uuid_evento_key', ['uuid_evento'])

    # ### end Alembic commands ###
