"""revisando tabla vista_imagen

Revision ID: f630b3d1a927
Revises: 0ab92a086bf4
Create Date: 2026-01-08 14:11:28.189487-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f630b3d1a927'
down_revision: Union[str, None] = '0ab92a086bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visita_imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'salida', name='tipo_imagen_visita'), nullable=True),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visita_imagenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visita_imagenes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visita_imagenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visita_imagenes_id'))

    op.drop_table('visita_imagenes')
    # ### end Alembic commands ###
