"""add_activo_columns_retry

Revision ID: 85e06a68a4e5
Revises: 038fcba9e070
Create Date: 2026-02-18 19:44:08.753107-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85e06a68a4e5'
down_revision: Union[str, None] = '038fcba9e070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escaneos_qr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid_evento', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('registrado_offline', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['uuid_evento'])

    with op.batch_alter_table('residenciales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activa', sa.Boolean(), server_default='true', nullable=False))
        batch_op.alter_column('tipo_entidad',
               existing_type=postgresql.ENUM('residencial', 'predio', 'industrial', 'instituto', 'empresa', name='tipo_entidad_enum'),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('residenciales', schema=None) as batch_op:
        batch_op.alter_column('tipo_entidad',
               existing_type=postgresql.ENUM('residencial', 'predio', 'industrial', 'instituto', 'empresa', name='tipo_entidad_enum'),
               server_default=sa.text("'residencial'::tipo_entidad_enum"),
               existing_nullable=False)
        batch_op.drop_column('activa')

    with op.batch_alter_table('escaneos_qr', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('registrado_offline')
        batch_op.drop_column('uuid_evento')

    # ### end Alembic commands ###
