"""agregando nuevos campos observacion e imagenes en visitas, placa_chasis y destino_visita en visitantes y nueva tabla llamada visita_imagenes

Revision ID: 7e236e30e3f0
Revises: 3187bfe9e1d4
Create Date: 2026-01-08 11:59:49.492423-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e236e30e3f0'
down_revision: Union[str, None] = '3187bfe9e1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placa_chasis', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('destino_visita', sa.String(), nullable=True))

    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('imagenes', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.drop_column('imagenes')
        batch_op.drop_column('observacion')

    with op.batch_alter_table('visitantes', schema=None) as batch_op:
        batch_op.drop_column('destino_visita')
        batch_op.drop_column('placa_chasis')

    # ### end Alembic commands ###
