"""delete imagenes to visitas, add observacion_entrada, observacion_salida to visitas and tipo to visita_imagen

Revision ID: 0ab92a086bf4
Revises: efbc98de1264
Create Date: 2026-01-08 12:55:17.700175-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab92a086bf4'
down_revision: Union[str, None] = 'efbc98de1264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visita_imagenes', schema=None) as batch_op:
        batch_op.drop_index('ix_visita_imagenes_id')

    op.drop_table('visita_imagenes')
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacion_entrada', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('observacion_salida', sa.Text(), nullable=True))
        batch_op.drop_column('imagenes')
        batch_op.drop_column('observacion')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacion', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('imagenes', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('observacion_salida')
        batch_op.drop_column('observacion_entrada')

    op.create_table('visita_imagenes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('visita_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], name='visita_imagenes_visita_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='visita_imagenes_pkey')
    )
    with op.batch_alter_table('visita_imagenes', schema=None) as batch_op:
        batch_op.create_index('ix_visita_imagenes_id', ['id'], unique=False)

    # ### end Alembic commands ###
