"""add_tipo_entidad_to_residencial

Revision ID: 038fcba9e070
Revises: 5b8a8a93abb9
Create Date: 2026-02-14 21:40:29.447727-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038fcba9e070'
down_revision: Union[str, None] = '5b8a8a93abb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    tipo_entidad_enum = sa.Enum('residencial', 'predio', 'industrial', 'instituto', 'empresa', name='tipo_entidad_enum')
    tipo_entidad_enum.create(op.get_bind(), checkfirst=True)
    
    with op.batch_alter_table('residenciales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_entidad', sa.Enum('residencial', 'predio', 'industrial', 'instituto', 'empresa', name='tipo_entidad_enum'), nullable=False, server_default='residencial'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residenciales', schema=None) as batch_op:
        batch_op.drop_column('tipo_entidad')

    # Drop enum type
    tipo_entidad_enum = sa.Enum('residencial', 'predio', 'industrial', 'instituto', 'empresa', name='tipo_entidad_enum')
    tipo_entidad_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
