"""creando tabla visita_imagen

Revision ID: 951d5542bf39
Revises: f630b3d1a927
Create Date: 2026-01-08 14:15:01.844806-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951d5542bf39'
down_revision: Union[str, None] = 'f630b3d1a927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("visita_imagenes")
     
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("visita_imagenes")
    # ### end Alembic commands ###
